# This is a config for E2B sandbox template.
# You can use template ID (wzsvzt36dx2hghlpgnti) or template name (elyria-test) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("elyria-test") # Sync sandbox
# sandbox = await AsyncSandbox.create("elyria-test") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('elyria-test')

team_id = "c95bacec-2def-496b-9468-d02fb68cb036"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "elyria-test"
template_id = "wzsvzt36dx2hghlpgnti"
